import Icon, {
  AndroidFilled,
  CloseOutlined,
  CloudUploadOutlined,
  CheckOutlined,
  CaretDownOutlined,
  CaretRightOutlined,
  DatabaseFilled,
  DashboardFilled,
  EyeOutlined,
  EditOutlined,
  FileFilled,
  FullscreenExitOutlined,
  FullscreenOutlined,
  ImportOutlined,
  MenuOutlined,
  StockOutlined,
  SecurityScanFilled,
  SearchOutlined,
  UserOutlined,
  WarningFilled,
  DownloadOutlined,
  DeleteFilled,
  EyeFilled,
  CalendarFilled,
  LockFilled,
} from "@ant-design/icons";

export {
  AndroidFilled,
  CloseOutlined,
  CloudUploadOutlined,
  CheckOutlined,
  CaretDownOutlined,
  CaretRightOutlined,
  DatabaseFilled,
  DashboardFilled,
  EyeOutlined,
  EditOutlined,
  FileFilled,
  FullscreenExitOutlined,
  FullscreenOutlined,
  ImportOutlined,
  MenuOutlined,
  StockOutlined,
  SecurityScanFilled,
  SearchOutlined,
  UserOutlined,
  WarningFilled,
  DownloadOutlined,
  DeleteFilled,
  EyeFilled,
  CalendarFilled,
  LockFilled,
};
export default Icon;
